import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { CreditCard, Mail, Save, Settings, Smartphone } from "lucide-react";
import { toast } from "sonner";

import { getAdminDashboard, saveAppSettings, savePaymentSettings } from "@/lib/admin-dashboard.functions";
import { Panel, SectionHeader, StatusBadge } from "./DashboardShared";

type Dashboard = Awaited<ReturnType<typeof getAdminDashboard>>;

export function SettingsPanel({ data }: { data: Dashboard }) {
  const saveApp = useServerFn(saveAppSettings);
  const savePayment = useServerFn(savePaymentSettings);
  const queryClient = useQueryClient();
  const [settings, setSettings] = useState(data.config.settings);
  const [smtp, setSmtp] = useState({ ...data.config.smtp, password: "" });
  const [payment, setPayment] = useState({ accessToken: "", mode: data.config.payments.mode as "sandbox" | "production", expirationMinutes: data.config.payments.expirationMinutes });
  const appMutation = useMutation({ mutationFn: () => saveApp({ data: { ...settings, smtp } }), onSuccess: () => { toast.success("Configurações publicadas no Firebase."); queryClient.invalidateQueries({ queryKey: ["admin-dashboard"] }); }, onError: () => toast.error("Falha ao salvar configurações.") });
  const paymentMutation = useMutation({ mutationFn: () => savePayment({ data: payment }), onSuccess: () => { toast.success("Mercado Pago configurado com segurança no servidor."); setPayment((current) => ({ ...current, accessToken: "" })); queryClient.invalidateQueries({ queryKey: ["admin-dashboard"] }); }, onError: () => toast.error("Falha ao salvar o Mercado Pago.") });
  const set = (key: keyof typeof settings, value: unknown) => setSettings((current) => ({ ...current, [key]: value }));

  return <section className="space-y-5">
    <SectionHeader title="Configurações" description="Integrações, distribuição e recursos remotos do aplicativo." />
    <ConfigTitle number="01" icon={CreditCard} title="Pagamentos" subtitle="Credenciais usadas exclusivamente no servidor." />
    <Panel className="p-4"><div className="flex items-center justify-between"><h3 className="font-semibold">Mercado Pago</h3><StatusBadge active={data.config.payments.configured} label={data.config.payments.configured ? "Configurado" : "Não configurado"} /></div><div className="mt-3 grid gap-3 md:grid-cols-3"><Field label="Access Token (vazio mantém o atual)"><input type="password" value={payment.accessToken} onChange={(event) => setPayment({ ...payment, accessToken: event.target.value })} placeholder={data.config.payments.configured ? "Token já configurado" : "APP_USR-..."} /></Field><Field label="Ambiente"><select value={payment.mode} onChange={(event) => setPayment({ ...payment, mode: event.target.value as "sandbox" | "production" })}><option value="sandbox">Sandbox</option><option value="production">Produção</option></select></Field><Field label="Expiração do PIX (minutos)"><input type="number" value={payment.expirationMinutes} onChange={(event) => setPayment({ ...payment, expirationMinutes: Number(event.target.value) })} /></Field></div><SaveButton pending={paymentMutation.isPending} onClick={() => paymentMutation.mutate()} label="Salvar pagamentos" /></Panel>

    <ConfigTitle number="02" icon={Settings} title="Conteúdo e comunidade" subtitle="Links atualizados no Firebase sem recompilar o aplicativo." />
    <Panel className="grid gap-3 p-4 md:grid-cols-2"><Field label="Canal do YouTube"><input value={settings.youtube} onChange={(event) => set("youtube", event.target.value)} placeholder="@canal ou URL" /></Field><Field label="Telegram"><input value={settings.telegram} onChange={(event) => set("telegram", event.target.value)} /></Field><Field label="WhatsApp"><input value={settings.whatsapp} onChange={(event) => set("whatsapp", event.target.value)} /></Field><Field label="Facebook"><input value={settings.facebook} onChange={(event) => set("facebook", event.target.value)} /></Field></Panel>

    <ConfigTitle number="03" icon={Mail} title="Acesso e e-mail" subtitle="Login Google e servidor SMTP para verificação e avisos." />
    <div className="grid gap-4 lg:grid-cols-2"><Panel className="p-4"><h3 className="font-semibold">Login com Google</h3><Field label="Web Client ID"><input value={settings.googleClientId} onChange={(event) => set("googleClientId", event.target.value)} placeholder="xxxx.apps.googleusercontent.com" /></Field></Panel><Panel className="p-4"><div className="flex justify-between"><h3 className="font-semibold">Verificação por e-mail (SMTP)</h3><StatusBadge active={data.config.smtp.passwordConfigured} label={data.config.smtp.passwordConfigured ? "Configurado" : "Pendente"} /></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Servidor SMTP"><input value={smtp.host} onChange={(event) => setSmtp({ ...smtp, host: event.target.value })} /></Field><Field label="Porta"><input type="number" value={smtp.port} onChange={(event) => setSmtp({ ...smtp, port: Number(event.target.value) })} /></Field><Field label="Usuário SMTP"><input value={smtp.username} onChange={(event) => setSmtp({ ...smtp, username: event.target.value })} /></Field><Field label="Senha (vazio mantém a atual)"><input type="password" value={smtp.password} onChange={(event) => setSmtp({ ...smtp, password: event.target.value })} /></Field><Field label="Nome do remetente"><input value={smtp.senderName} onChange={(event) => setSmtp({ ...smtp, senderName: event.target.value })} /></Field><Field label="E-mail do remetente"><input value={smtp.senderEmail} onChange={(event) => setSmtp({ ...smtp, senderEmail: event.target.value })} /></Field></div><label className="mt-3 flex gap-2 text-xs"><input type="checkbox" checked={smtp.secure} onChange={(event) => setSmtp({ ...smtp, secure: event.target.checked })} /> Conexão segura direta (normalmente porta 465)</label></Panel></div>

    <ConfigTitle number="04" icon={Smartphone} title="Aplicativo e distribuição" subtitle="Versão, atualização e disponibilidade das telas." />
    <div className="grid gap-4 lg:grid-cols-2"><Panel className="p-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Version code"><input type="number" value={settings.versionCode} onChange={(event) => set("versionCode", Number(event.target.value))} /></Field><Field label="Version name"><input value={settings.versionName} onChange={(event) => set("versionName", event.target.value)} /></Field></div><Field label="Novidades da versão"><textarea rows={5} value={settings.changelog} onChange={(event) => set("changelog", event.target.value)} /></Field><Field label="Link da Play Store ou APK"><input value={settings.downloadUrl} onChange={(event) => set("downloadUrl", event.target.value)} /></Field><label className="mt-3 flex gap-2 text-xs"><input type="checkbox" checked={settings.forceUpdate} onChange={(event) => set("forceUpdate", event.target.checked)} /> Exigir atualização</label></Panel><Panel className="p-4"><h3 className="font-semibold">Telas do aplicativo</h3>{([['store','Loja'],['videos','Vídeos'],['wallet','Carteira']] as const).map(([key,label]) => <label key={key} className="mt-3 flex items-center justify-between rounded-lg border border-border p-3 text-xs"><span>{label}</span><input type="checkbox" checked={settings.screens[key]} onChange={(event) => set("screens", { ...settings.screens, [key]: event.target.checked })} /></label>)}</Panel></div>
    <SaveButton pending={appMutation.isPending} onClick={() => appMutation.mutate()} label="Salvar configurações do aplicativo" />
  </section>;
}

function ConfigTitle({ number, icon: Icon, title, subtitle }: { number: string; icon: typeof Settings; title: string; subtitle: string }) { return <div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-lg bg-primary/15 text-xs font-bold text-primary">{number}</span><Icon className="size-5 text-primary" /><div><h3 className="font-bold">{title}</h3><p className="text-xs text-muted-foreground">{subtitle}</p></div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-[0.7rem] font-medium text-muted-foreground">{label}<div className="mt-1 [&>*]:w-full [&>*]:rounded-lg [&>*]:border [&>*]:border-input [&>*]:bg-background [&>*]:px-3 [&>*]:py-2 [&>*]:text-xs [&>*]:text-foreground [&>*]:outline-none">{children}</div></label>; }
function SaveButton({ pending, onClick, label }: { pending: boolean; onClick: () => void; label: string }) { return <button disabled={pending} onClick={onClick} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground disabled:opacity-50"><Save className="size-4" />{label}</button>; }
